paths:
  root: "../"
  input: "results/postal_worker_descriptions.csv"
  # input: "results/german_man_descriptions.csv"
  output: "results/postal_worker_chunks.csv"
  # output: "results/german_man_chunks.csv"
  embeddings: "data/embeddings/text/sdxl-turbo/postal_worker"

embeddings:
  model: "mxbai-embed-large"